# Generated by Django 2.0.4 on 2019-01-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Idea'), (1, 'Research'), (2, 'Strategy'), (3, 'Performance'), (4, 'Bugs'), (5, 'Buy')], default=0),
        ),
    ]
