# Generated by Django 2.0.4 on 2019-01-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190114_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='doneDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='modified',
            new_name='modifiedDate',
        ),
    ]
